# Numpy ( general purpose processing package, it provides high performance multi dimensional array object and tools for working with these arrays
## used for creating multidimensional arrays
### Numpy As inbuilt functions to do the operations with in arrays
#### Numpy has bindings of C and C++ libraries, so operations are pretty fast

In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4])   # to check signature of inbuilt func(shift+tab before bracket)

In [3]:
type(arr1)

numpy.ndarray

In [4]:
my_array=[1,2,3]

In [5]:
arr2=np.array(my_array)

In [6]:
type(arr2)

numpy.ndarray

In [7]:
print(arr2)

[1 2 3]


In [8]:
arr2.shape    # count of elements in 1D  # row and columns in other dimensions  # property vs function

(3,)

In [9]:
# multi dimensional array     
my_list1=[1,2,3,4]
my_list2=[5,6,7,8]
my_list3=[9,10,11,12]

In [10]:
arr3=np.array([my_list1,my_list2,my_list3])

In [11]:
arr3    # 1D - one opening and closing bracket # 2D- two opening and closing # easy way to identify

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
arr3.shape    # rows and columns

(3, 4)

In [13]:
# In most of EDA we will be working with 2D array
# the reason we are using array is, array processing is very fast
# whole Dataset in to array after featuring eng and selection and many process
# I can take that and apply to ML algorithm ,such that training takes up quickly 


In [14]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
arr6=arr3.reshape(4,3) # not changing actual array (reshape)

In [16]:
arr3.reshape(4,4) # and also make sure no.of elements is same

ValueError: cannot reshape array of size 12 into shape (4,4)

In [17]:
arr3.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [18]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
arr6

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Indexing (always imp to learn when ur learning new thing)

# acessing array elements

In [20]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
arr3[1][0]  # In two dim array

5

In [22]:
arr3[1] # respective two dim , giving only row info, it displays complete row  #important one

array([5, 6, 7, 8])

In [23]:
arr4=np.array([1,2,3,4,5])

In [24]:
arr4

array([1, 2, 3, 4, 5])

In [25]:
arr4[1]

2

In [26]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
arr3[:,:]     # arr3[row info(start:end), column info(start:end)]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
arr3[0:2,:]       # in both row and column info- next to : -it is excluded

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
arr3[:2,:2]

array([[1, 2],
       [5, 6]])

In [30]:
arr3[2:,2:]

array([[11, 12]])

In [31]:
arr5=np.arange(0,10)   #arange(start,stop,step) # stop(excluded) # creates 1D array

In [32]:
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(0,10,2,dtype=float)

array([0., 2., 4., 6., 8.])

In [34]:
np.linspace(1,5,10,dtype=int)  #equally divided (start,stop,number of points)  #used in DL

array([1, 1, 1, 2, 2, 3, 3, 4, 4, 5])

In [35]:
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# copy() function or broadcasting

arr5[3:]=30  

In [37]:
arr5

array([ 0,  1,  2, 30, 30, 30, 30, 30, 30, 30])

In [38]:
arr10=arr5

In [39]:
arr10

array([ 0,  1,  2, 30, 30, 30, 30, 30, 30, 30])

In [40]:
arr10[3:]=50

In [41]:
arr10

array([ 0,  1,  2, 50, 50, 50, 50, 50, 50, 50])

In [42]:
arr5                          # array is reference type (Sharing same memory)

array([ 0,  1,  2, 50, 50, 50, 50, 50, 50, 50])

In [43]:
# understand the difference b/w reference type and value type

# int variable( value type)
# array is reference type (Sharing same memory)

In [44]:
# to avoid this issue in array( we are using copy() function)

In [45]:
arr10

array([ 0,  1,  2, 50, 50, 50, 50, 50, 50, 50])

In [46]:
arr11=arr10.copy()

In [47]:
arr11

array([ 0,  1,  2, 50, 50, 50, 50, 50, 50, 50])

In [48]:
arr11[3:]=100

In [49]:
arr11

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [50]:
arr10  # no change, bcz of copy() , creating separte memory location while copying

array([ 0,  1,  2, 50, 50, 50, 50, 50, 50, 50])

In [51]:
# some conditions usefull in EDA

arr10

array([ 0,  1,  2, 50, 50, 50, 50, 50, 50, 50])

In [52]:
arr10*2  # we can perform all elementary operations on numpy array elements( +,-, /,%)

array([  0,   2,   4, 100, 100, 100, 100, 100, 100, 100])

In [53]:
arr10>2  # checks every elements return bool value

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [54]:
arr10

array([ 0,  1,  2, 50, 50, 50, 50, 50, 50, 50])

In [55]:
arr10[arr10<2]   # checks the array and returns elements based on condition provided

array([0, 1])

In [56]:
# create and reshape arrays

np.arange(1,9).reshape(2,4)    # two functions at a time

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
np.ones(4)  # by default flot values

array([1., 1., 1., 1.])

In [58]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [59]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
np.zeros(4)

array([0., 0., 0., 0.])

In [61]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [62]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [63]:
# random distribution # uniform distribution b/w [0 to 1]  #each an every time the values will change, as they are randomly selected
np.random.rand(2,3)

array([[0.15234638, 0.77764188, 0.95242505],
       [0.53694144, 0.71454766, 0.38480317]])

In [64]:
np.random.randn(2,3)  #standard normal distrb  #each an every time the values will change, as they are randomly selected

array([[ 1.44479616, -0.16899422, -0.57682639],
       [ 1.94979327,  0.83847224,  1.52053874]])

In [65]:
np.random.randint(0,10,8).reshape((2,4))  # 8 numbers b/w 0 to 10  #each an every time the values will change, as they are randomly selected

array([[9, 9, 6, 7],
       [3, 0, 0, 6]])

In [66]:
np.random.random_sample((1,5))

array([[0.74682231, 0.11438485, 0.20994069, 0.88573247, 0.30249215]])